'use strict';

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');

const vault = require('../src/services/vault');

const TMP = path.join(os.tmpdir(), 'spectre-vault-test-' + Date.now());

before(() => {
  vault.ensureDirs(TMP);
});

after(() => {
  fs.rmSync(TMP, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// writeAnalysis
// ---------------------------------------------------------------------------
describe('writeAnalysis', () => {
  it('creates file with correct name and frontmatter', () => {
    const now = new Date(2026, 2, 11, 8, 30, 0); // 2026-03-11 08:30
    const fpath = vault.writeAnalysis(
      {
        _date: now,
        composite_score: 42,
        tactical_brief: 'Elevated activity in eastern corridor.',
        findings: '- 3 vessels dark-running\n- Unusual clustering near OPL',
        actions: '- Deploy patrol to sector 7',
        anomalies: '- MMSI 123456789 speed anomaly',
      },
      TMP,
    );

    assert.ok(fs.existsSync(fpath), 'file should exist');
    assert.ok(path.basename(fpath).startsWith('2026-03-11-0830'), 'filename matches date pattern');

    const raw = fs.readFileSync(fpath, 'utf8');
    assert.ok(raw.includes('composite_score: 42'));
    assert.ok(raw.includes('threat_level: MEDIUM'));
    assert.ok(raw.includes('## Tactical Brief'));
    assert.ok(raw.includes('Elevated activity'));
    assert.ok(raw.includes('*Generated by SPECTRE AI Engine*'));
  });
});

// ---------------------------------------------------------------------------
// writeIncident
// ---------------------------------------------------------------------------
describe('writeIncident', () => {
  it('creates file with correct ID format', () => {
    const now = new Date(2026, 2, 11, 8, 30, 0);
    const fpath = vault.writeIncident(
      {
        _date: now,
        severity: 'CRITICAL',
        title: 'Dark vessel near anchorage',
        description: 'Vessel went AIS-dark at 08:25 near Eastern Anchorage.',
        entity_mmsi: '123456789',
      },
      TMP,
    );

    assert.ok(fs.existsSync(fpath), 'incident file should exist');
    const fname = path.basename(fpath);
    assert.match(fname, /^INC-\d{4}-\d{3}\.md$/, 'filename matches INC-YYYY-NNN.md');

    const raw = fs.readFileSync(fpath, 'utf8');
    assert.ok(raw.includes('severity: CRITICAL'));
    assert.ok(raw.includes('status: OPEN'));
    assert.ok(raw.includes('entity_mmsi: 123456789'));
    assert.ok(raw.includes('Dark vessel near anchorage'));
  });
});

// ---------------------------------------------------------------------------
// readRecentAnalyses
// ---------------------------------------------------------------------------
describe('readRecentAnalyses', () => {
  it('returns written analyses', () => {
    const results = vault.readRecentAnalyses(24, TMP);
    assert.ok(Array.isArray(results), 'should return array');
    assert.ok(results.length >= 1, 'should have at least 1 analysis');
    assert.ok(results[0].meta.composite_score != null, 'should have parsed score');
  });
});

// ---------------------------------------------------------------------------
// readOpenIncidents
// ---------------------------------------------------------------------------
describe('readOpenIncidents', () => {
  it('returns only OPEN incidents', () => {
    // Write a closed incident
    vault.writeIncident(
      {
        id: 'INC-2026-900',
        severity: 'LOW',
        status: 'CLOSED',
        title: 'Resolved incident',
        description: 'This was resolved.',
      },
      TMP,
    );

    const open = vault.readOpenIncidents(TMP);
    assert.ok(open.length >= 1, 'should have at least 1 open incident');
    for (const inc of open) {
      assert.equal(inc.meta.status, 'OPEN', 'all returned incidents should be OPEN');
    }
  });
});

// ---------------------------------------------------------------------------
// getVaultContext
// ---------------------------------------------------------------------------
describe('getVaultContext', () => {
  it('returns a non-empty string', () => {
    const ctx = vault.getVaultContext(3000, TMP);
    assert.ok(typeof ctx === 'string');
    assert.ok(ctx.length > 0, 'context should not be empty');
  });
});

// ---------------------------------------------------------------------------
// getNextIncidentId
// ---------------------------------------------------------------------------
describe('getNextIncidentId', () => {
  it('increments correctly', () => {
    const id1 = vault.getNextIncidentId(TMP);
    // Write an incident with that id so the next one increments
    vault.writeIncident({ id: id1, title: 'Test inc' }, TMP);
    const id2 = vault.getNextIncidentId(TMP);

    const num1 = parseInt(id1.split('-')[2], 10);
    const num2 = parseInt(id2.split('-')[2], 10);
    assert.equal(num2, num1 + 1, 'next ID should be previous + 1');
  });
});

// ---------------------------------------------------------------------------
// writeVesselNote
// ---------------------------------------------------------------------------
describe('writeVesselNote', () => {
  it('creates new vessel file and appends to it', () => {
    const mmsi = '999888777';
    const fpath = vault.writeVesselNote(
      mmsi,
      { vessel_name: 'MV TESTSHIP', note: 'First sighting' },
      TMP,
    );

    assert.ok(fs.existsSync(fpath));
    assert.ok(path.basename(fpath) === `MMSI-${mmsi}.md`);

    let raw = fs.readFileSync(fpath, 'utf8');
    assert.ok(raw.includes('MV TESTSHIP'));
    assert.ok(raw.includes('First sighting'));

    // Append
    vault.writeVesselNote(mmsi, { note: 'Second sighting at Changi' }, TMP);
    raw = fs.readFileSync(fpath, 'utf8');
    assert.ok(raw.includes('Second sighting at Changi'), 'appended note should exist');
  });
});

// ---------------------------------------------------------------------------
// readVesselHistory
// ---------------------------------------------------------------------------
describe('readVesselHistory', () => {
  it('reads existing vessel note', () => {
    const history = vault.readVesselHistory('999888777', TMP);
    assert.ok(history !== null);
    assert.equal(String(history.meta.mmsi), '999888777');
  });

  it('returns null for unknown vessel', () => {
    const history = vault.readVesselHistory('000000000', TMP);
    assert.equal(history, null);
  });
});

// ---------------------------------------------------------------------------
// updateIndex
// ---------------------------------------------------------------------------
describe('updateIndex', () => {
  it('creates SPECTRE-INDEX.md', () => {
    const fpath = vault.updateIndex(TMP);
    assert.ok(fs.existsSync(fpath));

    const raw = fs.readFileSync(fpath, 'utf8');
    assert.ok(raw.includes('# SPECTRE INDEX'));
    assert.ok(raw.includes('Analyses:'));
    assert.ok(raw.includes('Incidents:'));
  });
});

// ---------------------------------------------------------------------------
// writeDailySummary
// ---------------------------------------------------------------------------
describe('writeDailySummary', () => {
  it('creates daily summary file', () => {
    const fpath = vault.writeDailySummary(
      '2026-03-11',
      { total_analyses: 5, incidents_opened: 1, overview: 'Busy day.' },
      TMP,
    );
    assert.ok(fs.existsSync(fpath));
    assert.ok(path.basename(fpath) === '2026-03-11.md');
  });
});

// ---------------------------------------------------------------------------
// writeWeeklySummary
// ---------------------------------------------------------------------------
describe('writeWeeklySummary', () => {
  it('creates weekly summary file', () => {
    const fpath = vault.writeWeeklySummary(
      11,
      { year: 2026, total_analyses: 30, overview: 'Stable week.' },
      TMP,
    );
    assert.ok(fs.existsSync(fpath));
    assert.ok(path.basename(fpath) === 'week-2026-11.md');
  });
});
