'use strict';

const fs = require('fs');
const path = require('path');
const config = require('../config');

const VAULT = path.resolve(config.VAULT_PATH);

const DIRS = [
  'analyses',
  'incidents',
  'vessels',
  'daily-summaries',
  'weekly-summaries',
  'patterns',
];

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

function ensureDirs(base) {
  const root = base || VAULT;
  if (!fs.existsSync(root)) fs.mkdirSync(root, { recursive: true });
  for (const d of DIRS) {
    const p = path.join(root, d);
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
  }
}

function pad(n) {
  return String(n).padStart(2, '0');
}

function localISO(date) {
  const d = date || new Date();
  const off = -d.getTimezoneOffset();
  const sign = off >= 0 ? '+' : '-';
  const hh = pad(Math.floor(Math.abs(off) / 60));
  const mm = pad(Math.abs(off) % 60);
  return (
    d.getFullYear() +
    '-' + pad(d.getMonth() + 1) +
    '-' + pad(d.getDate()) +
    'T' + pad(d.getHours()) +
    ':' + pad(d.getMinutes()) +
    ':' + pad(d.getSeconds()) +
    sign + hh + ':' + mm
  );
}

function friendlyDate(date) {
  const d = date || new Date();
  return (
    d.getFullYear() +
    '-' + pad(d.getMonth() + 1) +
    '-' + pad(d.getDate()) +
    ' ' + pad(d.getHours()) +
    ':' + pad(d.getMinutes())
  );
}

function fileDate(date) {
  const d = date || new Date();
  return (
    d.getFullYear() +
    '-' + pad(d.getMonth() + 1) +
    '-' + pad(d.getDate()) +
    '-' + pad(d.getHours()) + pad(d.getMinutes())
  );
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: content };
  const meta = {};
  for (const line of match[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (!isNaN(Number(val)) && val !== '') val = Number(val);
    meta[key] = val;
  }
  return { meta, body: match[2] };
}

function threatLabel(score) {
  if (score >= 80) return 'CRITICAL';
  if (score >= 60) return 'HIGH';
  if (score >= 40) return 'MEDIUM';
  if (score >= 20) return 'LOW';
  return 'MINIMAL';
}

function formatList(items) {
  if (!items) return null;
  if (typeof items === 'string') return items;
  if (Array.isArray(items) && items.length > 0) {
    return items.map((item) => `- ${item}`).join('\n');
  }
  return null;
}

function formatAnomalies(items) {
  if (!items) return null;
  if (typeof items === 'string') return items;
  if (Array.isArray(items) && items.length > 0) {
    return items
      .map((a) => `- **${a.mmsi || 'Unknown'}**: ${a.reason || 'No reason given'}`)
      .join('\n');
  }
  return null;
}

function getISOWeek(d) {
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  date.setUTCDate(date.getUTCDate() + 4 - (date.getUTCDay() || 7));
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.ceil(((date - yearStart) / 86400000 + 1) / 7);
}

// ---------------------------------------------------------------------------
// Write operations
// ---------------------------------------------------------------------------

function writeAnalysis(data, base) {
  const root = base || VAULT;
  ensureDirs(root);
  const now = data._date || new Date();
  const score = data.composite_score != null ? data.composite_score : 0;
  const level = data.threat_level || threatLabel(score);
  const fname = fileDate(now) + '.md';
  const fpath = path.join(root, 'analyses', fname);

  const content = [
    '---',
    `timestamp: ${localISO(now)}`,
    `composite_score: ${score}`,
    `threat_level: ${level}`,
    '---',
    `# Analysis — ${friendlyDate(now)}`,
    '',
    `## Threat Score: ${score}/100 (${level})`,
    '',
    '## Tactical Brief',
    data.tactical_brief || '_No brief provided._',
    '',
    '## Key Findings',
    formatList(data.key_findings) || formatList(data.findings) || '_None._',
    '',
    '## Priority Actions',
    formatList(data.priority_actions) || formatList(data.actions) || '_None._',
    '',
    '## Vessel Anomalies',
    formatAnomalies(data.vessel_anomalies) || formatList(data.anomalies) || '_None._',
    '',
    '## Forecast',
    `**6h:** ${data.forecast_6h || '_Unavailable._'}`,
    `**24h:** ${data.forecast_24h || '_Unavailable._'}`,
    '',
    '---',
    '*Generated by SPECTRE AI Engine*',
    '',
  ].join('\n');

  fs.writeFileSync(fpath, content, 'utf8');
  return fpath;
}

function getNextIncidentId(base) {
  const root = base || VAULT;
  const dir = path.join(root, 'incidents');
  ensureDirs(root);
  const year = new Date().getFullYear();
  const prefix = `INC-${year}-`;

  let max = 0;
  if (fs.existsSync(dir)) {
    const files = fs.readdirSync(dir).filter((f) => f.startsWith(prefix));
    for (const f of files) {
      const m = f.match(/INC-\d{4}-(\d{3})/);
      if (m) {
        const n = parseInt(m[1], 10);
        if (n > max) max = n;
      }
    }
  }
  return `${prefix}${String(max + 1).padStart(3, '0')}`;
}

function writeIncident(alert, base) {
  const root = base || VAULT;
  ensureDirs(root);
  const now = alert._date || new Date();
  const id = alert.id || getNextIncidentId(root);
  const severity = alert.severity || 'MEDIUM';
  const status = alert.status || 'OPEN';
  const title = alert.title || 'Untitled Incident';
  const description = alert.description || '_No details._';
  const mmsi = alert.entity_mmsi || '';
  const fname = id + '.md';
  const fpath = path.join(root, 'incidents', fname);

  const content = [
    '---',
    `id: ${id}`,
    `severity: ${severity}`,
    `status: ${status}`,
    `created: ${localISO(now)}`,
    `entity_mmsi: ${mmsi}`,
    '---',
    `# ${id} — ${title}`,
    '',
    '## Details',
    description,
    '',
    '## Timeline',
    `- ${friendlyDate(now)} — Incident created`,
    '',
  ].join('\n');

  fs.writeFileSync(fpath, content, 'utf8');
  return fpath;
}

function writeVesselNote(mmsi, data, base) {
  const root = base || VAULT;
  ensureDirs(root);
  const fname = `MMSI-${mmsi}.md`;
  const fpath = path.join(root, 'vessels', fname);
  const now = data._date || new Date();

  if (fs.existsSync(fpath)) {
    const entry = `\n- ${friendlyDate(now)} — ${data.note || 'Update'}\n`;
    fs.appendFileSync(fpath, entry, 'utf8');
  } else {
    const content = [
      '---',
      `mmsi: ${mmsi}`,
      `vessel_name: ${data.vessel_name || 'UNKNOWN'}`,
      `created: ${localISO(now)}`,
      '---',
      `# Vessel ${data.vessel_name || mmsi}`,
      '',
      '## Observations',
      `- ${friendlyDate(now)} — ${data.note || 'Initial observation'}`,
      '',
    ].join('\n');
    fs.writeFileSync(fpath, content, 'utf8');
  }
  return fpath;
}

function writeDailySummary(date, data, base) {
  const root = base || VAULT;
  ensureDirs(root);
  const d = typeof date === 'string' ? date : date.toISOString().slice(0, 10);
  const fname = d + '.md';
  const fpath = path.join(root, 'daily-summaries', fname);

  const content = [
    '---',
    `date: ${d}`,
    `total_analyses: ${data.total_analyses || 0}`,
    `incidents_opened: ${data.incidents_opened || 0}`,
    `average_threat: ${data.average_threat || 0}`,
    '---',
    `# Daily Summary — ${d}`,
    '',
    '## Overview',
    data.overview || '_No summary._',
    '',
    '## Key Events',
    data.key_events || '_None._',
    '',
    '## Statistics',
    data.statistics || '_None._',
    '',
  ].join('\n');

  fs.writeFileSync(fpath, content, 'utf8');
  return fpath;
}

function writeWeeklySummary(weekNum, data, base) {
  const root = base || VAULT;
  ensureDirs(root);
  const year = data.year || new Date().getFullYear();
  const wk = String(weekNum).padStart(2, '0');
  const fname = `week-${year}-${wk}.md`;
  const fpath = path.join(root, 'weekly-summaries', fname);

  const content = [
    '---',
    `year: ${year}`,
    `week: ${weekNum}`,
    `total_analyses: ${data.total_analyses || 0}`,
    `incidents_opened: ${data.incidents_opened || 0}`,
    '---',
    `# Weekly Summary — ${year} W${wk}`,
    '',
    '## Overview',
    data.overview || '_No summary._',
    '',
    '## Trends',
    data.trends || '_None._',
    '',
  ].join('\n');

  fs.writeFileSync(fpath, content, 'utf8');
  return fpath;
}

function updateIndex(base) {
  const root = base || VAULT;
  ensureDirs(root);

  const count = (dir) => {
    const d = path.join(root, dir);
    if (!fs.existsSync(d)) return 0;
    return fs.readdirSync(d).filter((f) => f.endsWith('.md')).length;
  };

  const latest = (dir, n) => {
    const d = path.join(root, dir);
    if (!fs.existsSync(d)) return [];
    return fs
      .readdirSync(d)
      .filter((f) => f.endsWith('.md'))
      .sort()
      .reverse()
      .slice(0, n);
  };

  const now = new Date();
  const lines = [
    '# SPECTRE INDEX',
    '',
    `*Last updated: ${friendlyDate(now)}*`,
    '',
    '## Vault Statistics',
    `- Analyses: ${count('analyses')}`,
    `- Incidents: ${count('incidents')}`,
    `- Vessel Notes: ${count('vessels')}`,
    `- Daily Summaries: ${count('daily-summaries')}`,
    `- Weekly Summaries: ${count('weekly-summaries')}`,
    '',
    '## Latest Analyses',
    ...latest('analyses', 5).map((f) => `- [[analyses/${f}|${f}]]`),
    '',
    '## Latest Incidents',
    ...latest('incidents', 5).map((f) => `- [[incidents/${f}|${f}]]`),
    '',
  ];

  const fpath = path.join(root, 'SPECTRE-INDEX.md');
  fs.writeFileSync(fpath, lines.join('\n'), 'utf8');
  return fpath;
}

// ---------------------------------------------------------------------------
// Read operations
// ---------------------------------------------------------------------------

function readRecentAnalyses(hours, base) {
  hours = hours || 24;
  const root = base || VAULT;
  const dir = path.join(root, 'analyses');
  if (!fs.existsSync(dir)) return [];

  const cutoff = Date.now() - hours * 3600 * 1000;
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse();

  const results = [];
  for (const f of files) {
    if (results.length >= 10) break;
    const fpath = path.join(dir, f);
    const stat = fs.statSync(fpath);
    if (stat.mtimeMs < cutoff) continue;
    const raw = fs.readFileSync(fpath, 'utf8');
    const parsed = parseFrontmatter(raw);
    results.push({ file: f, ...parsed });
  }
  return results;
}

function readOpenIncidents(base) {
  const root = base || VAULT;
  const dir = path.join(root, 'incidents');
  if (!fs.existsSync(dir)) return [];

  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.md'));
  const results = [];
  for (const f of files) {
    const raw = fs.readFileSync(path.join(dir, f), 'utf8');
    const parsed = parseFrontmatter(raw);
    if (parsed.meta.status === 'OPEN') {
      results.push({ file: f, ...parsed });
    }
  }
  return results;
}

function readVesselHistory(mmsi, base) {
  const root = base || VAULT;
  const fpath = path.join(root, 'vessels', `MMSI-${mmsi}.md`);
  if (!fs.existsSync(fpath)) return null;
  const raw = fs.readFileSync(fpath, 'utf8');
  return parseFrontmatter(raw);
}

function readPatterns(base) {
  const root = base || VAULT;
  const dir = path.join(root, 'patterns');
  if (!fs.existsSync(dir)) return [];

  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.md'));
  return files.map((f) => {
    const raw = fs.readFileSync(path.join(dir, f), 'utf8');
    return { file: f, ...parseFrontmatter(raw) };
  });
}

function getVaultContext(maxTokens, base) {
  maxTokens = maxTokens || 3000;
  const root = base || VAULT;
  const parts = [];
  let est = 0;

  // Rough token estimate: ~4 chars per token
  const charBudget = maxTokens * 4;

  // Last 12 analyses
  const analyses = readRecentAnalyses(168, root).slice(0, 12);
  if (analyses.length > 0) {
    parts.push('## Recent Analyses');
    for (const a of analyses) {
      const summary =
        a.body.length > 300 ? a.body.slice(0, 300) + '...' : a.body;
      const entry = `### ${a.file}\nScore: ${a.meta.composite_score || '?'} | Level: ${a.meta.threat_level || '?'}\n${summary}\n`;
      est += entry.length;
      if (est > charBudget) break;
      parts.push(entry);
    }
  }

  // Open incidents
  const incidents = readOpenIncidents(root);
  if (incidents.length > 0 && est < charBudget) {
    parts.push('## Open Incidents');
    for (const inc of incidents) {
      const entry = `- ${inc.meta.id || inc.file}: ${inc.meta.severity || '?'} (${inc.meta.entity_mmsi || 'N/A'})\n`;
      est += entry.length;
      if (est > charBudget) break;
      parts.push(entry);
    }
  }

  // Vessel notes (just list them)
  const vdir = path.join(root, 'vessels');
  if (fs.existsSync(vdir) && est < charBudget) {
    const vfiles = fs.readdirSync(vdir).filter((f) => f.endsWith('.md'));
    if (vfiles.length > 0) {
      parts.push('## Tracked Vessels');
      for (const f of vfiles.slice(0, 20)) {
        const entry = `- ${f.replace('.md', '')}\n`;
        est += entry.length;
        if (est > charBudget) break;
        parts.push(entry);
      }
    }
  }

  return parts.join('\n');
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  ensureDirs,
  writeAnalysis,
  writeIncident,
  writeVesselNote,
  writeDailySummary,
  writeWeeklySummary,
  updateIndex,
  readRecentAnalyses,
  readOpenIncidents,
  readVesselHistory,
  readPatterns,
  getVaultContext,
  getNextIncidentId,
  // Exposed for testing with custom base path
  _parseFrontmatter: parseFrontmatter,
};
